// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migaddnewcloumnincontact : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migaddnewcloumnincontact));
        
        string IMigrationMetadata.Id
        {
            get { return "202212201910157_mig-addnewcloumnincontact"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
